name = "GaussianFilters"
uuid = "08d575fb-911d-541e-8431-6cfa767e7851"
authors = ["Arec Jamgochian <arec.jamgochian@gmail.com>"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "^1.0"

[extras]
NBInclude = "0db19996-df87-5ea3-a455-e3a50d440464"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["NBInclude", "Plots", "Test"]
